// Code generated by go-swagger; DO NOT EDIT.

package student

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Cinojose/StudentEnrollmentApi/models"
)

// FindStudentsByStatusOKCode is the HTTP code returned for type FindStudentsByStatusOK
const FindStudentsByStatusOKCode int = 200

/*FindStudentsByStatusOK successful operation

swagger:response findStudentsByStatusOK
*/
type FindStudentsByStatusOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Student `json:"body,omitempty"`
}

// NewFindStudentsByStatusOK creates FindStudentsByStatusOK with default headers values
func NewFindStudentsByStatusOK() *FindStudentsByStatusOK {

	return &FindStudentsByStatusOK{}
}

// WithPayload adds the payload to the find students by status o k response
func (o *FindStudentsByStatusOK) WithPayload(payload []*models.Student) *FindStudentsByStatusOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find students by status o k response
func (o *FindStudentsByStatusOK) SetPayload(payload []*models.Student) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindStudentsByStatusOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Student, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// FindStudentsByStatusBadRequestCode is the HTTP code returned for type FindStudentsByStatusBadRequest
const FindStudentsByStatusBadRequestCode int = 400

/*FindStudentsByStatusBadRequest Invalid status value

swagger:response findStudentsByStatusBadRequest
*/
type FindStudentsByStatusBadRequest struct {
}

// NewFindStudentsByStatusBadRequest creates FindStudentsByStatusBadRequest with default headers values
func NewFindStudentsByStatusBadRequest() *FindStudentsByStatusBadRequest {

	return &FindStudentsByStatusBadRequest{}
}

// WriteResponse to the client
func (o *FindStudentsByStatusBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
