// Code generated by go-swagger; DO NOT EDIT.

package student

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewFindStudentsByStatusParams creates a new FindStudentsByStatusParams object
// no default values defined in spec.
func NewFindStudentsByStatusParams() FindStudentsByStatusParams {

	return FindStudentsByStatusParams{}
}

// FindStudentsByStatusParams contains all the bound params for the find students by status operation
// typically these are obtained from a http.Request
//
// swagger:parameters findStudentsByStatus
type FindStudentsByStatusParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*find by id of the student
	  In: query
	*/
	ID *int64
	/*Find students by class
	  In: query
	*/
	Class *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewFindStudentsByStatusParams() beforehand.
func (o *FindStudentsByStatusParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qID, qhkID, _ := qs.GetOK("Id")
	if err := o.bindID(qID, qhkID, route.Formats); err != nil {
		res = append(res, err)
	}

	qClass, qhkClass, _ := qs.GetOK("class")
	if err := o.bindClass(qClass, qhkClass, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindID binds and validates parameter ID from query.
func (o *FindStudentsByStatusParams) bindID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("Id", "query", "int64", raw)
	}
	o.ID = &value

	return nil
}

// bindClass binds and validates parameter Class from query.
func (o *FindStudentsByStatusParams) bindClass(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Class = &raw

	return nil
}
