// Code generated by go-swagger; DO NOT EDIT.

package student

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdateStudentOKCode is the HTTP code returned for type UpdateStudentOK
const UpdateStudentOKCode int = 200

/*UpdateStudentOK Student updated

swagger:response updateStudentOK
*/
type UpdateStudentOK struct {
}

// NewUpdateStudentOK creates UpdateStudentOK with default headers values
func NewUpdateStudentOK() *UpdateStudentOK {

	return &UpdateStudentOK{}
}

// WriteResponse to the client
func (o *UpdateStudentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// UpdateStudentMethodNotAllowedCode is the HTTP code returned for type UpdateStudentMethodNotAllowed
const UpdateStudentMethodNotAllowedCode int = 405

/*UpdateStudentMethodNotAllowed Invalid input

swagger:response updateStudentMethodNotAllowed
*/
type UpdateStudentMethodNotAllowed struct {
}

// NewUpdateStudentMethodNotAllowed creates UpdateStudentMethodNotAllowed with default headers values
func NewUpdateStudentMethodNotAllowed() *UpdateStudentMethodNotAllowed {

	return &UpdateStudentMethodNotAllowed{}
}

// WriteResponse to the client
func (o *UpdateStudentMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}
