// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Student enrollment
//
//  Student enrollment service
//  Schemes:
//    http
//    https
//  Host: student.beanscode.io
//  BasePath: /v2
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//    - application/xml
//
//  Produces:
//    - application/json
//    - application/xml
//
// swagger:meta
package restapi
